USE cs542_cars;

DROP TABLE IF EXISTS manager;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS model_simple;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS password;