INSERT INTO company (companyid, companyname, country) VALUES ('1','Toyota','Japan');
INSERT INTO company (companyid, companyname, country) VALUES ('2','Honda','Japan');
INSERT INTO company (companyid, companyname, country) VALUES ('3','Mazada','Japan');
INSERT INTO company (companyid, companyname, country) VALUES ('4','Ford','US');
INSERT INTO company (companyid, companyname, country) VALUES ('5','Buick','US');
INSERT INTO company (companyid, companyname, country) VALUES ('6','Jeep','US');
INSERT INTO company (companyid, companyname, country) VALUES ('7','BMW','German');
INSERT INTO company (companyid, companyname, country) VALUES ('8','Audi','German');
INSERT INTO company (companyid, companyname, country) VALUES ('9','VolksWagen','German');
